config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: "static#portfolio"

  devise_for :users

  resources :items
  resources :posts

  get 'blog', to: 'static#blog'
  get 'portfolio', to: 'static#portfolio'
  get 'about', to: 'static#about'
  get 'contact', to: 'static#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset
  include Ckeditor::Orm::Mongoid::AssetBase
  include Mongoid::Paperclip
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_mongoid_attached_file :data,
                            url: '/ckeditor_assets/attachments/:id/:filename',
                            path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_mongoid_attached_file :data,
                            url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                            path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                            styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_presence :data
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :title, type: String
  field :description,  type: String
  field :body,  type: String

  has_mongoid_attached_file :image
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :title, type: String
  field :description,  type: String
  field :body,  type: String

  has_mongoid_attached_file :image
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:image, :title, :description, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit( :image, :title, :description, :body )
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def blog
    @posts = Post.all
  end

  def portfolio
    @items = Item.all
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/items/_form.html.slim
= form_for @item, :html => {:class => 'mdl-grid'} do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .mdl-cell.mdl-cell--12-col.mdl-card__supporting-text.no-padding
    .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label.full_width
      input#title.mdl-textfield__input[type="text" name="item[title]" value="#{@item.title}"]
      label.mdl-textfield__label[for="title"]
        =t :item_title
  .mdl-cell.mdl-cell--12-col.mdl-card__supporting-text.no-padding
    .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label.full_width
      input#description.mdl-textfield__input[type="text" name="item[description]" value="#{@item.description}" ]
      label.mdl-textfield__label[for="description"]
        =t :item_decription
  = cktext_area :item, :body, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' }, value: @item.body
  h3.mdl-cell.mdl-cell--12-col.mdl-typography--headline
    | Установка картинки
  .mdl-cell.mdl-cell--12-col.mdl-card__supporting-text.no-padding
    .file_input
      label.image_input_button.mdl-button.mdl-js-button.mdl-button--fab.mdl-button--mini-fab.mdl-js-ripple-effect.mdl-button--colored
        i.material-icons file_upload
        input#file_input_file.none[type="file" name="item[image]"  value="#{@item.image}" ]
    #file_input_text_div.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
      input#file_input_text.file_input_text.mdl-textfield__input[type="text"disabled readonly]
      label.mdl-textfield__label[for="file_input_text"]
        - if @item.image_file_name
          =@item.image_file_name
      .hidden
        = f.file_field :image
    - if @item.image
      h3.mdl-cell.mdl-cell--12-col.mdl-typography--headline
        | Картинка, установленная сейчас
      .mdl-card__media
        img.article-image[src="#{@item.image.url}" border="0" alt=""]
  .mdl-card__actions.mdl-card--border
    a.mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect[href="#{items_path}"]
      | назад
    input.mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.mdl-button--accent[type="submit"]

javascript:
  $(function() {
    var fileInputTextDiv = document.getElementById('file_input_text_div');
    var fileInput = document.getElementById('file_input_file');
    var fileInputText = document.getElementById('file_input_text');
    fileInput.addEventListener('change', changeInputText);
    fileInput.addEventListener('change', changeState);

    function changeInputText() {
      var str = fileInput.value;
      var i;
      if (str.lastIndexOf('\\')) {
        i = str.lastIndexOf('\\') + 1;
      } else if (str.lastIndexOf('/')) {
        i = str.lastIndexOf('/') + 1;
      }
      fileInputText.value = str.slice(i, str.length);
    }

    function changeState() {
      if (fileInputText.value.length != 0) {
        if (!fileInputTextDiv.classList.contains("is-focused")) {
          fileInputTextDiv.classList.add('is-focused');
        }
      } else {
        if (fileInputTextDiv.classList.contains("is-focused")) {
          fileInputTextDiv.classList.remove('is-focused');
        }
      }
    }
  });

app/views/items/edit.html.slim
.mdl-grid.portfolio-max-width
  .mdl-cell.mdl-cell--12-col.mdl-card.mdl-shadow--4dp
    .mdl-card__title
      h2.mdl-card__title-text
        | Редактирование
    .mdl-grid
      == render 'form'
/ = link_to 'Show', @item
/ '|
/ = link_to 'Back', items_path

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.title
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Item', new_item_path
= link_to 'Logout', destroy_user_session_path, method: :delete

app/views/items/new.html.slim
.mdl-grid.portfolio-max-width
  .mdl-cell.mdl-cell--12-col.mdl-card.mdl-shadow--4dp
    .mdl-card__title
      h2.mdl-card__title-text
        | New Item
    .mdl-cell.mdl-cell--12-col.portfolio-copy
      == render 'form'

app/views/items/show.html.slim
.mdl-grid.portfolio-max-width
  .mdl-cell.mdl-cell--12-col.mdl-card.mdl-shadow--4dp
    .mdl-card__title
      h2.mdl-card__title-text
        =@item.title
    .mdl-card__media
      img.article-image[src="#{@item.image.url}" border="0" alt=""]
    .mdl-card__supporting-text
      strong
        = @item.description
    .mdl-grid.portfolio-copy.item_width
      .mdl-cell.mdl-cell--12-col
        = @item.body.html_safe
      / h3.mdl-cell.mdl-cell--12-col.mdl-typography--headline
      /   | Introduction
      / .mdl-cell.mdl-cell--6-col.mdl-card__supporting-text.no-padding
      /   p
      /     |  Excepteur reprehenderit sint exercitation ipsum consequat qui sit id velit elit. Velit anim eiusmod labore sit amet. Voluptate voluptate irure occaecat deserunt incididunt esse in. Sunt velit aliquip sunt elit ex nulla reprehenderit qui ut eiusmod ipsum do. Duis veniam reprehenderit laborum occaecat id proident nulla veniam. Duis enim deserunt voluptate aute veniam sint pariatur exercitation. Irure mollit est sit labore est deserunt pariatur duis aute laboris cupidatat. Consectetur consequat esse est sit veniam adipisicing ipsum enim irure. 
      / .mdl-cell.mdl-cell--6-col
      /   img.article-image[src=" images/portfolio-example-02.jpg" border="0" alt=""]
      / h3.mdl-cell.mdl-cell--12-col.mdl-typography--headline
      /   | Initial Ideas
      / .mdl-cell.mdl-cell--6-col
      /   img.article-image[src=" images/portfolio-example-03.jpg" border="0" alt=""]
      / .mdl-cell.mdl-cell--6-col.mdl-card__supporting-text.no-padding
      /   p
      /     |  Excepteur reprehenderit sint exercitation ipsum consequat qui sit id velit elit. Velit anim eiusmod labore sit amet. Voluptate voluptate irure occaecat deserunt incididunt esse in. Sunt velit aliquip sunt elit ex nulla reprehenderit qui ut eiusmod ipsum do. Duis veniam reprehenderit laborum occaecat id proident nulla veniam. Duis enim deserunt voluptate aute veniam sint pariatur exercitation. Irure mollit est sit labore est deserunt pariatur duis aute laboris cupidatat. Consectetur consequat esse est sit veniam adipisicing ipsum enim irure. 
      / h3.mdl-cell.mdl-cell--12-col.mdl-typography--headline
      /   | Final Concept
      / .mdl-cell.mdl-cell--6-col
      /   img.article-image[src=" images/portfolio-example-05.jpg" border="0" alt=""]
      / .mdl-cell.mdl-cell--6-col
      /   img.article-image[src=" images/portfolio-example-06.jpg" border="0" alt=""]
      / .mdl-cell.mdl-cell--8-col.mdl-card__supporting-text.no-padding
      /   p
      /     |  Excepteur reprehenderit sint exercitation ipsum consequat qui sit id velit elit. Velit anim eiusmod labore sit amet. Voluptate voluptate irure occaecat deserunt incididunt esse in. Sunt velit aliquip sunt elit ex nulla reprehenderit qui ut eiusmod ipsum do. Duis veniam reprehenderit laborum occaecat id proident nulla veniam. Duis enim deserunt voluptate aute veniam sint pariatur exercitation. Irure mollit est sit labore est deserunt pariatur duis aute laboris cupidatat. Consectetur consequat esse est sit veniam adipisicing ipsum enim irure. 
        
/ = link_to 'Edit', edit_item_path(@item)
/ '|
/ = link_to 'Back', items_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content=("A portfolio template that uses Material Design Lite.") name="description" /
    meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0" name="viewport" /

    title
      =t :app


    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
    link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet" /
    link href="https://code.getmdl.io/1.2.1/material.grey-pink.min.css" rel="stylesheet" /
  body
    .mdl-layout.mdl-js-layout.mdl-layout--fixed-header
      =render "shared/header"
      main.mdl-layout__content
        =yield
        =render "shared/footer"
    / script src="https://code.getmdl.io/1.2.1/material.min.js" 

app/views/posts/_form.html.slim
= form_for(post) do |f|
  - if post.errors.any?
    #error_explanation
      h2
        = pluralize(post.errors.count, "error")
        | prohibited this post from being saved:
      ul
        - post.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :body
    = f.text_field :body
  .actions
    = f.submit

app/views/posts/edit.html.slim
.mdl-grid.portfolio-max-width
  .mdl-cell.mdl-cell--12-col.mdl-card.mdl-shadow--4dp
    .mdl-card__title
      h2.mdl-card__title-text
        | Редактирование
    .mdl-grid
      == render 'form', post: @post 
/ = link_to 'Show', @item
/ '|
/ = link_to 'Back', items_path

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.slim
.mdl-grid.portfolio-max-width
  .mdl-cell.mdl-cell--12-col.mdl-card.mdl-shadow--4dp
    .mdl-card__title
      h2.mdl-card__title-text
        | New Post
    .mdl-cell.mdl-cell--12-col.portfolio-copy
      == render 'form'

app/views/posts/show.html.slim
p#notice= notice
p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body
p
  strong Description:
  = @post.description
p
  strong image:
  =image_tag @post.image.url
= link_to 'Edit', edit_post_path(@post)
= link_to 'Back', posts_path

app/views/shared/_footer.slim
footer.mdl-mini-footer
  .mdl-mini-footer__left-section
    .mdl-logo
      =t :brand
  .mdl-mini-footer__right-section
    ul.mdl-mini-footer__link-list
      li
        a href="#"
          =t :help
      li
        a href="#"
          =t :terms

app/views/shared/_header.html.slim
header.mdl-layout__header.mdl-layout__header--waterfall.portfolio-header
  .mdl-layout__header-row.portfolio-logo-row
    span.mdl-layout__title
      .portfolio-logo
      span.mdl-layout__title
        =t :brand
  .mdl-layout__header-row.portfolio-navigation-row.mdl-layout--large-screen-only
    nav.mdl-navigation.mdl-typography--body-1-force-preferred-font
      a.mdl-navigation__link href="#{portfolio_path}"
        =t :portfolio
      a.mdl-navigation__link href="#{blog_path}"
        =t :blog
      a.mdl-navigation__link href="#{about_path}"
        =t :about
      a.mdl-navigation__link href="#{contact_path}"
        =t :contact
.mdl-layout__drawer.mdl-layout--small-screen-only
  nav.mdl-navigation.mdl-typography--body-1-force-preferred-font
    a.mdl-navigation__link href="#{portfolio_path}"
      =t :portfolio
    a.mdl-navigation__link href="#{blog_path}"
      =t :blog
    a.mdl-navigation__link href="#{about_path}"
      =t :about
    a.mdl-navigation__link href="#{contact_path}"
      =t :contact

app/views/shared/_main.slim
.mdl-grid.portfolio-max-width
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work01.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Blog template
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work07.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Sunt nulla
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work02.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Android.com website
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work03.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Dashboard template
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work04.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Text-heavy website
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work08.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Ex officia laborum
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work05.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Stand-alone article
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work06.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text MDL website
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more
  .mdl-cell.mdl-card.mdl-shadow--4dp.portfolio-card
    .mdl-card__media
      img.article-image alt="" border="0" src=(" images/example-work09.jpg") /
    .mdl-card__title
      h2.mdl-card__title-text Consequat ut quis
    .mdl-card__supporting-text
      | Enim labore aliqua consequat ut quis ad occaecat aliquip incididunt. Sunt nulla eu enim irure enim nostrud aliqua consectetur ad consectetur sunt ullamco officia. Ex officia laborum et consequat duis.
    .mdl-card__actions.mdl-card--border
      a.mdl-button.mdl-button--colored.mdl-js-button.mdl-js-ripple-effect.mdl-button--accent href="portfolio-example01.html"  Read more